# Generated by Django 2.0.13 on 2019-03-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[(1, 'プログラミング'), (2, '料理'), (3, 'ゲーム'), (4, '映画'), (5, 'その他')], default='プログラミング', max_length=10),
        ),
    ]
