# Generated by Django 2.0.13 on 2019-03-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('プログラミング', 'Programming'), ('料理', 'Cooking'), ('ゲーム', 'Game'), ('映画', 'Movie'), ('その他', 'others')], default='プログラミング', max_length=10),
        ),
    ]
