# Generated by Django 2.0.13 on 2019-04-09 14:11

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_post_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
