# Generated by Django 2.0.13 on 2019-04-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20190409_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_len',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_len', models.CharField(max_length=200)),
            ],
        ),
    ]
