# Generated by Django 2.0.13 on 2019-04-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20190413_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('プログラミング', 'Programming'), ('料理', 'Cooking'), ('ゲーム', 'Game'), ('映画', 'Movie'), ('その他', 'others')], default='プログラミング', max_length=10, verbose_name='カテゴリー名'),
        ),
    ]
